### ISSUE TITLE
Store should be cleared after each request

### ISSUE THREAD

**Issue by afn** [steveklabnik/request_store#23]
In the interest of avoiding memory leaks, it would be prudent to clear the RequestStore not just before, but also after, each request.

Thanks!
Tony

**Comment by wbotelhos** [comment]
Hi,

Since this commit, I lose my `asset_host` value, so my `image_url`, for example, comes relative:
From `http://test.host/assets/image.png` to `assets/image.png`

If I put back `RequestStore.clear!` before `@app.call(env)`, it works.
