### ISSUE TITLE
Storage is still thread-local

### ISSUE THREAD

**Issue by rusterholz** [steveklabnik/request_store#39]
So, let me start by saying that I love this gem, my team loves this gem, and the "issue" I'm describing is pretty much purely-theoretical at this point. We're not experiencing any problems with the gem in any of our environments. This "issue" is more of a general inquiry.

Before discovering this gem, we had been using callbacks in our Rails ApplicationController (`before_action` and `after_action`) to set context values in `Thread.current` and then clear them at the end of the request. Currently our production environment is running on non-threading app servers, so we had never seen any problems with this, but we have been considering moving to a threading server. When we found this gem, we were grateful because we felt that using it would eliminate potential issues that might arise with `Thread.current` if/when we switch to a threading server.

However, today I started looking through the code of this gem, and I find that, rather than being tied to the Rack request, the data stored by this gem is stored in ... _drumroll please_ ... `Thread.current`!

/picard_facepalm.

So here are my two questions:
1. The README.md states -- quite explicitly -- that using this gem is supposed to be an improvement over setting values in `Thread.current`. Since the gem stores the data in `Thread.current` anyway, and since we were using a callback to clear the data at the end of the request, what exactly is the advantage of using this gem over using `Thread.current` directly?
2. How can this gem truly guarantee that data is request-local instead of thread-local? More specifically, how would this gem ensure that data was still local to a specific request if it were running on a (hypothetical) app server handling more than one request per thread? (AFAIK no such app server exists at present, but we can imagine one.)
   - Is there a way to uniquely identify the current Rack request -- some kind of Rack request id number, if you will? Because it strikes me that simply using that number as a sub-key within `store` would solve this concern, e.g. `Thread.current[:request_store][ rack_request_id ]`.
   - There's also the possibility of monkey-patching the Rack request object directly, and storing data directly in that object. This feels inelegant, but it would clearly provide a guarantee of request-local storage.

I would be happy to write up a PR implementing either of those latter options, if you think one is more viable, but I haven't looked into doing so because I know next-to-nothing about Rack, so I'd like to hear back from you before beginning any such work.

Thanks for your time!

**Comment by steveklabnik** [comment]
Hey @rusterholz ! You caught me when I was travelling, apologies for the delay.

I think the crux of it is this:

> (AFAIK no such app server exists at present, but we can imagine one.) 

I can totally understand your concerns here, and it's true, this is a weakness of the design. But this is because it's just a response to how Ruby web servers currently work. If said imaginary server ever became real and popular, I'd consider changing how it works to be correct in those servers.

> what exactly is the advantage of using this gem over using Thread.current directly?

Is the example description in the README not enough? Could I make it more clear somehow?

**Comment by justin808** [comment]
@steveklabnik Can you elaborate on your comment:

> But this is because it's just a response to how Ruby web servers currently work.

Could you possibly paint some color over the intricacies of these parts to those of us that are super familiar with Rack:

https://github.com/steveklabnik/request_store/blob/master/lib/request_store/railtie.rb 

https://github.com/steveklabnik/request_store/blob/master/lib/request_store/middleware.rb

**Comment by steveklabnik** [comment]
Basically, servers like Thin re-use threads across requests. That's the issue. Imagine a thread pool, and each incoming request gets assigned a thread. When the request is done, the thread goes back to the pool, and gets used in another request later. So any TLS data persists. So the middleware makes sure to clear the state out.That's it.

The parent is basically asking "What happens if multiple threads serve the same request," which is something that I'm not sure any servers actually do, and would require code changes on my part.

**Comment by justin808** [comment]
@steveklabnik How do the servers re-use the same thread (seems like during anything like I/O)? And how does your code solve that from Rack integration? What is TLS data.

**Comment by steveklabnik** [comment]
> How do the servers re-use the same thread 

As I described, in a thread pool.

> And how does your code solve that from Rack integration? 

After each request, it ensures that the storage has been cleared.

> What is TLS data.

Thread local storage.

**Comment by justin808** [comment]
Could two requests, using the same key still collide? Consider the paper_trail case: https://github.com/airblade/paper_trail/issues/499#issuecomment-83175865. 

There must be some secret sauce that makes it so you don't have to do something like:

```
Thread.current[:request_store][ rack_request_id ]
```

**Comment by d-snp** [comment]
Just a small not really necessary addition to your discussion: There is at least one Ruby web server that runs multiple concurrent requests per thread and that's Reel. Reel doesn't implement the Rack standard so it's not really relevant here. You say thin reuses threads, so I'll take your word for it, but I'm actually surprised it doesn't run multiple concurrent requests per thread as well. I would be surprised if Goliath doesn't either as they're both built on EventMachine and at least Goliath advertises it runs requests in fibers, not threads.

I'm a bit confused why information is stored in the thread state at all, why not just in the Rack env? That's guaranteed to be only accessible by your current app, and you can put anything you like in there under I suspect any application server. Not criticizing at all, just wondering if I'm missing something about the Rack env.

**Comment by steveklabnik** [comment]
> You say thin reuses threads, so I'll take your word for it,

It's entirely based off of trying it out, I haven't actually read Thin's code.

> I'm a bit confused why information is stored in the thread state at all, why not just in the Rack env?

That is an option for storing things, but people reach to TLS at times. I'm not saying it's even a good idea, I'm just here to help people out.

**Comment by d-snp** [comment]
I wondered why your code works in Thin so I researched a bit and found this issue:

https://bugs.ruby-lang.org/issues/5750

Seems like TLS is also Fiber local. That makes your solution work with basically any Ruby concurrency framework. I took a better look at this app and I get why you can't use Rack.env. Your api simply works everywhere which is rather powerful.

So, jay no bugs ;) does that satisfy you @rusterholz?

**Comment by justin808** [comment]
@steveklabnik I figured out my issue. Basically, it comes down to:

1. TLS is persisted between requests on some app servers which is probably not what you want.
2. RequestStore ensures that any keys are cleared between requests.

Somehow, I had misinterpreted some log messages where it erroneously seemed that multiple threads with the same thread ID were running concurrently, which, upon retrospect, is impossible.

Thanks for the help.

**Comment by justin808** [comment]
@steveklabnik Is your solution in RequestStore any different than if `RequestStore.clear!` is called as the first before hook in the ApplicationController? I can think of the following differences:

1. Using a controller hook allows this behavior in controller specs. Otherwise, you can call `RequestStore.clear!` before invoking controller actions in controller spec. Any way to automate that for controller specs? That would be a nice addition to this gem.
2. Using RequestStore would prevent errors from forgetting to use the hook mentioned in 1) at the cost of there being issues with ControllerSpecs.

**Comment by steveklabnik** [comment]
Rack Middleware is conceptually the correct place to put this, as it gets cleared really early in the lifetime of the request. Furthermore, it would be less portable, as only Rails has `ApplicationController`, whereas this works with all rack-based frameworks.

**Comment by rusterholz** [comment]
@steveklabnik First, my apologies -- I didn't mean to bring down a storm upon your head.

I agree that the Rack middleware is probably the safest place from which to clear the TLS -- certainly more portable, and arguably less prone to developer error, than clearing it from a rails controller callback. That answers my main question.

Still, I can't help but say I'd sleep a little better at night if something like the above suggestion could be implemented: `Thread.current[:request_store][ rack_request_id ]` -- not because I disagree with the argument that the current code is good enough for all current Rack-based app servers, but because it would be nice to have a truly explicit guarantee that storage will always be request-local no matter what app servers may be running this code in the future.

So here are my questions at this time:

1. Do you see any potential negative impacts resulting from adding the `rack_request_id` as a sub-key? (Obviously each fetch from RequestStore would incur a second hash lookup, but the penalty there should be only a handful of microseconds at most -- not even a millisecond -- and I generally find that acceptable.)
2. If I wrote a PR implementing the above, would you consider merging it?

**Comment by rusterholz** [comment]
@justin808 With regard to your question about using this in controller specs, I just added `RequestStore.clear!` to a `config.after(:each)` block in our `spec_helper.rb` and everything seems to be working just fine.

**Comment by ElMassimo** [comment]
I have implemented a store that can share variables between threads for the same request, we plan to enable concurrency in our Passenger servers, and we needed a solution that didn't have a big impact in our codebase (for legacy reasons).

It's called [`request_store_rails`](https://github.com/ElMassimo/request_store_rails). It's still in an experimental phase, so the API may change and things may break.

Let me know if you find it useful :smiley:

**Comment by steveklabnik** [comment]
I'm going to close this issue, as the discussion wound down years ago :)
