### ISSUE TITLE
Addition to support clearing RequestStore for Controller Specs

### ISSUE THREAD

**Issue by justin808** [steveklabnik/request_store#40]
In my conversion to using request_store, controller specs were depending on a before hook in the controllers to do the clear. I'd like to propose that I submit a PR that contains the following:
1. Spec Helper to include that calls RequestStore.clear!:

```
module RequestStoreSupport
  # Override process to call clear, since that is done if Rack is available
  def process(*)
    RequestStore.clear!
    super
  end
end
```
1. Update the README to suggest adding this line to spec_helper.rb or rails_helper.rb

```
  config.include RequestStoreSupport, type: :controller
```

This was modeled after the way Devise::TestHelpers is done.

If this sounds good, I'll create a PR. This solution seems to be working for me.

**Comment by steveklabnik** [comment]
I think this makes more sense as something like https://github.com/steveklabnik/request_store#no-rails--racktest than as code.

**Comment by justin808** [comment]
@steveklabnik Are you confident that your approach would work for controller specs? And does my approach not get used for request and feature specs?
