### ISSUE TITLE
request to follow SemVer/mention it in README

### ISSUE THREAD

**Issue by pravi** [steveklabnik/request_store#43]
Do you follow semantic versioning defined at semver.org? If yes, can you mention it in README. If not, can you consider it?

**Comment by steveklabnik** [comment]
I do. I thought it was basically assumed that gems followed semver _unless_ they said otherwise, since Bundler etc relies on that behavior.

I would accept a PR to add it to the README if you'd like :)

**Comment by pravi** [comment]
@steveklabnik I wish that was true. Apps like gitlab specify exact patch release in their Gemfile. gitlab wants ~? 1.2.0 and redmine wants 1.1.0. If we know you are following SemVer, we can convince them to just say ~> 1.1 and both can satisfy. I'm packaging gitlab for debian and we try to keep a single version of gem at a time and make sure all apps works with that version (yes, I know its a challenging task, but we want to make it easy for users to install apps using the package manager they are already familiar with). I will send a PR.

**Comment by steveklabnik** [comment]
Cool, make sense :+1:
