### ISSUE TITLE
rails 5.0.0.alpha

### ISSUE THREAD

**Issue by msroot** [steveklabnik/request_store#46]
I am trying RequestStore with rails 5 and it seems it doent work
```
>> RequestStore.store[:foo] = :bar
=> :bar
>>  RequestStore.store[:foo]
=> nil
>>
```

**Comment by msroot** [comment]
Ok the problem it happens when i run rails in development and as i see here https://github.com/steveklabnik/request_store/blob/master/lib/request_store/railtie.rb#L12 is cleaning 
`ActionDispatch.const_defined?(:Reloader)` 

But it would be nice if i can explicitly say if i want to clean

```ruby 

if ActionDispatch.const_defined?(:Reloader) && 
ActionDispatch::Reloader.respond_to?(:to_cleanup) && 
!RequestStore.skip_cleanup
        ActionDispatch::Reloader.to_cleanup do
          RequestStore.clear!
        end
      end

```

**Comment by steveklabnik** [comment]
It should only clean when you call `reload!`, i thought.

**Comment by u007** [comment]
any updates on this issue?

**Comment by steveklabnik** [comment]
I haven't used rails 5, so I don't know what's going on.

**Comment by u007** [comment]
this is related?
W, [2016-03-08T03:04:44.800053 #11389]  WARN -- : DEPRECATION WARNING: to_cleanup is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_complete instead). (called from block in <class:Railtie> at /usr/local/rvm/gems/ruby-2.2.4/bundler/gems/request_store-7993a21200ac/lib/request_store/railtie.rb:11)

**Comment by steveklabnik** [comment]
Yes, that sounds like it. I would be happy to take a patch to fix this; I'm not sure I'll have time to look until next week.

**Comment by steveklabnik** [comment]
1.3.1 should have fixed this, give it a try!

**Comment by msroot** [comment]
@steveklabnik thanks :)
