### ISSUE TITLE
Question: How this differs from ruby memoization?

### ISSUE THREAD

**Issue by imechemi** [steveklabnik/request_store#56]
hi, I was looking to save expensive service calls in my project and found that there are various ways to do that. But I have a problem with differentiating request_store from memoization. After reading about these on forums and blogs, I found that both spans for a one request/response cycle. 

Can someone help me with understanding the main difference between the two? 

Sorry for misusing the issue. I would really be grateful if someone can guide me. thank you :)

**Comment by steveklabnik** [comment]
"Memoization" is a general software programming technique. This gem provides "request local" storage. They're not _really_ comparable, exactly. Something like thread-local storage is one way to implement memoization, but that's an implementation detail.
