### ISSUE TITLE
Storing doesn't work with Rails6

### ISSUE THREAD

**Issue by patdec** [steveklabnik/request_store#70]
Same issue as #46 with Ruby on Rails 6 and ruby 2.7 

I get this

```ruby
>> RequestStore.store[:foo] = :bar
=> :bar
>>  RequestStore.store[:foo]
=> nil
>>
```

**Comment by steveklabnik** [comment]
It is likely that the integration doesn't work because Rails internals changed.

I don't write Rails anymore, so I don't know how to fix this, but I would be happy to merge a PR + cut a release.

**Comment by Fivell** [comment]
@steveklabnik  ruby 2.5  is ok , seems not about Rails
```
2.5.5 :001 >  RequestStore.store[:foo] = :bar
 => :bar 
2.5.5 :002 > RequestStore.store[:foo]
 => :bar 
2.5.5 :003 > Rails.version
 => "6.0.3.2" 
2.5.5 :004 >  RequestStore::VERSION
 => "1.5.0" 
2.5.5 :005 > 
```

@patdec  which version of RequestStore are you using?

**Comment by patdec** [comment]
I use RequestStore 1.5.0

**Comment by patdec** [comment]
Ok. I debugged with better_errors until now.  And I every time RequestStore.store[:foo] returned nil. But with binding,pry it works :)  

I use Docker in my development environment then it's more convenient to use better_errors gem than attach a new terminal to the active container with Pry.

It works, but I can't figure out this issue with better_errors.
