### ISSUE TITLE
Do you have plan for new release?

### ISSUE THREAD

**Issue by mkmn** [steveklabnik/request_store#91]
I'd like to use https://github.com/steveklabnik/request_store/pull/90.
Could you release a new version of the gem.

**Comment by steveklabnik** [comment]
Hi there! I am happy to cut a release, but it looks like CI is now failing for reasons that are *probably* not real (older ruby can't be used with newer bundler), and I'd like to fix that before doing so. If you want to help move that along, I would take a PR, and if not, I will try to get to it sometime soon, though no promises. Sorry about that!

**Comment by steveklabnik** [comment]
I have decided to simply drop old rubies from CI, and have cut 1.6.0 with the changes. Thank you for your patience.
